# # Font # #
font_family   Iosevka Nerd
# bold_font          JetBrainsMono Nerd Font Bold
# italic_font        JetBrainsMono Nerd Font Italic
# bold_italic_font   JetBrainsMono Nerd Font Bold Italic
font_size 12.0

# Make font less thick
# legacy, platform
text_composition_strategy legacy



# # BEHAVIOUR # #
# Copy selected text without pressing the shortcut
copy_on_select yes

# Close with Ctrl + D
close_on_child_death yes



# # TABS # #
tab_separator " - "
# bottom, top
tab_bar_edge bottom

# fade, separator, powerline, none
tab_bar_style powerline

# Title
active_tab_title_template ▶ {index}: {title}
inactive_tab_title_template   {index}: {title}


# # CURSOR # #
# none = reverse video effect
# cursor #ff7f7f
# cursor_text_color #111111

# To use block, beam and underline
shell_integration no-cursor

# block, beam, underline
cursor_shape underline

cursor_beam_thickness 1.5
cursor_underline_thickness 2.0

cursor_blink_interval -1
cursor_stop_blinking_after 15.0






# # KEYBINDS # #
# Open new windo at the same directory
map ctrl+shift+n new_os_window_with_cwd

# Vim keybindings
map ctrl+shift+l next_tab
map ctrl+shift+h previous_tab




# # SCROLLBACK # #
scrollback_lines 100000

# Number of lines scrolled by the mouse wheel and touchpad
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 1.0

# Scroll multiplier only takes effect after it reaches this number
wheel_scroll_min_lines 1





# # MOUSE # #
# Hide mouse cursor after the specified number of seconds
mouse_hide_wait 3.0
# url_color #d65c9d

# none, straight, doouble, curly, dotted, dashed
url_style dotted

open_url_with default

# Detected URLs are highlighted with an underline and changes mouse cursor
detect_urls yes

#url_excluded_characteres

# Show actual URL when the mouse hovers over a terminal hyperlink
show_hyperlink_targets yes

# hover, always, never
underline_hyperlinks always

# Remove spaces at the end of lines when copying to clipboard
# always, never, smart (will do it when using normal selections)
strip_trailing_spaces smart

# Set the active window to the window under the mouse
focus_follows_mouse yes


# Defult shape of the mouse pointer
default_pointer_shape beam

# The shape of the mouse pointer when the program running in the terminal grabs the mouse
pointer_shape_when_grabbed arrow

pointer_shape_when_dragging beam





# # TERMINAL BELL # #
enable_audio_bell no





# # WINDOW LAYOUT # #
remember_window_size no

initial_window_width  640
initial_window_height 400


window_resize_step_cells 1
window_resize_step_lines 1

draw_minimal_borders yes





# # Theme # #
# term xterm-256color
# foreground #f8f8f2
# background #000000
# selection_foreground #000000
# selection_background #f8f8f2

background_opacity 0.95
# background_opacity 0.8
dynamic_background_opacity no

# 0 - 64
background_blur 0

# path to png image
background_image none

# tiled, mirror_tiled, scaled, clamped, centered or cscaled
# background_image tiled

background_tint 0.0





# # ADVANCED # #

# Notify when a long process finishes
# never, unfocused, always | How many seconds is a long process | notify, bell
#notify_on_cmd_finish always 5 notify
notify_on_cmd_finish never



# # COLOR TABLE # #


# BEGIN_KITTY_THEME
# Cherry Midnight
include current-theme.conf
# END_KITTY_THEME

# Overwrite theme
# foreground #E3E3EA
# background #101017
cursor #FF7F7F
tab_bar_background #47B35D


# Tab styling
tab_bar_font_size 12.0
active_tab_background   #111111
active_tab_foreground   #ffffff
inactive_tab_background #212121
inactive_tab_foreground #888888
tab_bar_background      #000000
